#!/usr/bin/env python

"""
Usage: ./01.width.py <ctab> <prefix>

- Create file with chr start and end t_name FPKM width
- Calculate mean and std. dev. of width
- Visualize distribution
"""

import sys
import pandas as pd

df = pd.read_csv( sys.argv[1], sep="\t" )
#print df.head()
df["width"] = df["end"] - df["start"] + 1

coi = [ "chr", "start", "end", "t_name", "FPKM", "width" ]

print df[coi].head()

#To save time, we aren't getting rid of extra things 
#Like row number and stuff like that
#Should do it though 

print "Mean %d, std dev %d" % ( df["width"].mean(), df["width"].std() )

import matplotlib.pyplot as plt

plt.figure()
plt.hist( df["width"], bins=100, range=[0,10000] )
plt.savefig( sys.argv[2] + ".png")
plt.close()

#plt.figure()
#plt.savefig()
#plt.close()