#!/usr/bin/env python

"""
Reads a peptide sequence and puts the nucleotide sequence from a .fasta file. Puts three -'s for every blank in the peptide
./02-peptide_to_nucleotide <homolog.fa> <peptide_alignment.fa>
"""
import sys
import fasta

nuc = open(sys.argv[1])
pep = open(sys.argv[2])

pep_sequence = []
fasta_identifier = []

for ident, sequences in fasta.FASTAReader( pep ):
    pep_sequence.append(sequences)
    fasta_identifier.append(ident)
    
nuc_sequence = []

for ident, sequences in fasta.FASTAReader( nuc ):
    nuc_sequence.append(sequences)      
    
for i in range(len(pep_sequence)):
    codon_pos = 0
    new_seq = "" 
    print ">" + fasta_identifier[i]
    for p in pep_sequence[i]:
        if p == "-":
            new_seq += "---"
        else:
            new_seq += nuc_sequence[i][codon_pos:codon_pos+3]
            codon_pos += 3
    print new_seq